### ISSUE TITLE
Increase input size to show more than 4 digits at a time

### ISSUE THREAD

**Issue by ghost** [WPChill/gutenberg-forms#130]
Hello.
(Browser: Mozilla Firefox)

The input size of values on the sidebar is small, even on higher screen resolutions.
It currently shows only 4 numbers at a time.

In the example below:
- the number 0 is correctly displayed as 0.
- the number 10.000 is correctly inserted as 10.000 since recent updates, however the input size displays only 4 from its digits at a time. The actual value is wrongly perceived as 1.000.
![image](https://user-images.githubusercontent.com/61061987/81016703-5219f600-8e37-11ea-9d7a-542fd0cf5291.png)

**Comment by munirkamal** [comment]
We are using the Gutenberg component for all our options. This is how this input component works for the Gutenberg default blocks as well.

Rather than tweaking it in the plugin, I will report it to the Gutenberg repo.

![Screen Recording 2020-05-05 at 05 55 PM](https://user-images.githubusercontent.com/5817882/81068446-d339c180-8ef9-11ea-8a7a-d271c368c82e.gif)

**Comment by cristianraiber** [comment]
This has been implemented in core Gutenberg.
